info:
  app:
    name: Retail OCP API Gateway

server:
  port: 9000

zuul:
  routes:
    orders-service:
      path: /orders/**
    host:
      connect-timeout-millis: 5000
      socket-timeout-millis: 10000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: ${ocp.services.eureka.credentials.uri:http://localhost:8761}/eureka/
    
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${ocp.application.uris[0]}
    nonSecurePort: 80
