info:
  app:
<<<<<<< HEAD
    name: Retail OCP microservice
    description: Microservice
  
=======
    name: Ecommerce microservice
    description: Microservice
  
>>>>>>> branch 'master' of https://github.com/hsiangbinhua/retail-config.git
