---
spring:
  application:
    name: discovery
  profiles: eureka-primary
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护模式
  instance:
    hostname: eureka-discovery
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8771/eureka/,http://eureka-tertiary:8781/eureka/
---
spring:
  application:
    name: discovery
  profiles: eureka-secondary
server:
  port: 8771
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护模式
  instance:
    hostname: eureka-discovery
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-tertiary:8781/eureka/
---
spring:
  application:
    name: discovery
  profiles: eureka-tertiary
server:
  port: 8781
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护模式
  instance:
    hostname: eureka-discovery
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-secondary:8771/eureka/