---
spring:
  application:
    name: eureka-server-clustered
  profiles: eureka-primary
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-primary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8771/eureka/,http://eureka-tertiary:8781/eureka/
---
spring:
  application:
    name: eureka-server-clustered
  profiles: eureka-secondary
server:
  port: 8771
eureka:
  instance:
    hostname: eureka-secondary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8761/eureka/,http://eureka-tertiary:8781/eureka/
---
spring:
  application:
    name: eureka-server-clustered
  profiles: eureka-tertiary
server:
  port: 8781
eureka:
  instance:
    hostname: eureka-tertiary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8761/eureka/,http://eureka-tertiary:8771/eureka/