server:
  port: 8761

<<<<<<< HEAD
eureka:
  instance:
    hostname: ${ocp.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      
---
=======
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      
---

spring:
  profiles: docker
>>>>>>> branch 'master' of https://github.com/hsiangbinhua/retail-config.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
