info:
  app:
    name: Retail OCP Orders service
    description: Retail OCP Orders Microservice

server:
  port: 8083

spring:
  jpa:
   hibernate:
      ddl-auto: create-drop
      
eureka:
  instance:
    preferIpAddress: true
    hostname: ${ocp.application.uris[0]}
    nonSecurePort: 10080
  client:
    serviceUrl:
      defaultZone: ${ocp.services.eureka.credentials.uri:http://localhost:8761}/eureka/
      
spring:
  profiles: cloud

